language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -Ur requirements.txt
  - pip install coveralls
# command to run tests, e.g. python setup.py test
before_script:
  - python manage.test.py syncdb
  - python manage.test.py migrate
script:
  - coverage run --source='.' --branch --omit='*migrations*' manage.test.py test
after_success:
  - coverage report